"""add user_id to tasks

Revision ID: effc150c6d10
Revises: 
Create Date: 2026-06-21 16:30:13.905400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'effc150c6d10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_Tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'User_Tasks', 'user_table', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User_Tasks', type_='foreignkey')
    op.drop_column('User_Tasks', 'user_id')
    # ### end Alembic commands ###
